# Generated by Django 2.1.7 on 2020-05-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abscence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
