# Generated by Django 2.1.7 on 2020-05-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abscence', '0002_student_cin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='imagePath',
            field=models.CharField(default='default.jpg', max_length=50),
        ),
    ]
