# Generated by Django 2.1.7 on 2020-05-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abscence', '0003_auto_20200524_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='imagePath',
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='', upload_to='students'),
            preserve_default=False,
        ),
    ]
