# Generated by Django 2.1.7 on 2020-05-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abscence', '0004_auto_20200526_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
        migrations.AddField(
            model_name='student',
            name='imagePath',
            field=models.CharField(default='default.jpg', max_length=50),
        ),
    ]
